//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MyStoreIntegrationSBAPI.SO643000 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ScreenSoap", Namespace="http://www.acumatica.com/typed/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Filter[]))]
    public partial class Screen : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ClearOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProcessStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetScenarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetBusinessDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetLocaleNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchemaModeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Screen() {
            this.Url = global::MyStoreIntegrationSBAPI.Properties.Settings.Default.MyStoreIntegrationSBAPI_SO643000_Screen;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ClearCompletedEventHandler ClearCompleted;
        
        /// <remarks/>
        public event GetProcessStatusCompletedEventHandler GetProcessStatusCompleted;
        
        /// <remarks/>
        public event GetScenarioCompletedEventHandler GetScenarioCompleted;
        
        /// <remarks/>
        public event GetSchemaCompletedEventHandler GetSchemaCompleted;
        
        /// <remarks/>
        public event SetSchemaCompletedEventHandler SetSchemaCompleted;
        
        /// <remarks/>
        public event ExportCompletedEventHandler ExportCompleted;
        
        /// <remarks/>
        public event ImportCompletedEventHandler ImportCompleted;
        
        /// <remarks/>
        public event SubmitCompletedEventHandler SubmitCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event SetBusinessDateCompletedEventHandler SetBusinessDateCompleted;
        
        /// <remarks/>
        public event SetLocaleNameCompletedEventHandler SetLocaleNameCompleted;
        
        /// <remarks/>
        public event SetSchemaModeCompletedEventHandler SetSchemaModeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/Clear", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Clear() {
            this.Invoke("Clear", new object[0]);
        }
        
        /// <remarks/>
        public void ClearAsync() {
            this.ClearAsync(null);
        }
        
        /// <remarks/>
        public void ClearAsync(object userState) {
            if ((this.ClearOperationCompleted == null)) {
                this.ClearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearOperationCompleted);
            }
            this.InvokeAsync("Clear", new object[0], this.ClearOperationCompleted, userState);
        }
        
        private void OnClearOperationCompleted(object arg) {
            if ((this.ClearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/GetProcessStatus", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProcessResult GetProcessStatus() {
            object[] results = this.Invoke("GetProcessStatus", new object[0]);
            return ((ProcessResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetProcessStatusAsync() {
            this.GetProcessStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetProcessStatusAsync(object userState) {
            if ((this.GetProcessStatusOperationCompleted == null)) {
                this.GetProcessStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProcessStatusOperationCompleted);
            }
            this.InvokeAsync("GetProcessStatus", new object[0], this.GetProcessStatusOperationCompleted, userState);
        }
        
        private void OnGetProcessStatusOperationCompleted(object arg) {
            if ((this.GetProcessStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProcessStatusCompleted(this, new GetProcessStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/GetScenario", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Command[] GetScenario(string scenario) {
            object[] results = this.Invoke("GetScenario", new object[] {
                        scenario});
            return ((Command[])(results[0]));
        }
        
        /// <remarks/>
        public void GetScenarioAsync(string scenario) {
            this.GetScenarioAsync(scenario, null);
        }
        
        /// <remarks/>
        public void GetScenarioAsync(string scenario, object userState) {
            if ((this.GetScenarioOperationCompleted == null)) {
                this.GetScenarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScenarioOperationCompleted);
            }
            this.InvokeAsync("GetScenario", new object[] {
                        scenario}, this.GetScenarioOperationCompleted, userState);
        }
        
        private void OnGetScenarioOperationCompleted(object arg) {
            if ((this.GetScenarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScenarioCompleted(this, new GetScenarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/GetSchema", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Content GetSchema() {
            object[] results = this.Invoke("GetSchema", new object[0]);
            return ((Content)(results[0]));
        }
        
        /// <remarks/>
        public void GetSchemaAsync() {
            this.GetSchemaAsync(null);
        }
        
        /// <remarks/>
        public void GetSchemaAsync(object userState) {
            if ((this.GetSchemaOperationCompleted == null)) {
                this.GetSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSchemaOperationCompleted);
            }
            this.InvokeAsync("GetSchema", new object[0], this.GetSchemaOperationCompleted, userState);
        }
        
        private void OnGetSchemaOperationCompleted(object arg) {
            if ((this.GetSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSchemaCompleted(this, new GetSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/SetSchema", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSchema(Content schema) {
            this.Invoke("SetSchema", new object[] {
                        schema});
        }
        
        /// <remarks/>
        public void SetSchemaAsync(Content schema) {
            this.SetSchemaAsync(schema, null);
        }
        
        /// <remarks/>
        public void SetSchemaAsync(Content schema, object userState) {
            if ((this.SetSchemaOperationCompleted == null)) {
                this.SetSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchemaOperationCompleted);
            }
            this.InvokeAsync("SetSchema", new object[] {
                        schema}, this.SetSchemaOperationCompleted, userState);
        }
        
        private void OnSetSchemaOperationCompleted(object arg) {
            if ((this.SetSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchemaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/Export", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] Export(Command[] commands, Filter[] filters, int topCount, bool includeHeaders, bool breakOnError) {
            object[] results = this.Invoke("Export", new object[] {
                        commands,
                        filters,
                        topCount,
                        includeHeaders,
                        breakOnError});
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void ExportAsync(Command[] commands, Filter[] filters, int topCount, bool includeHeaders, bool breakOnError) {
            this.ExportAsync(commands, filters, topCount, includeHeaders, breakOnError, null);
        }
        
        /// <remarks/>
        public void ExportAsync(Command[] commands, Filter[] filters, int topCount, bool includeHeaders, bool breakOnError, object userState) {
            if ((this.ExportOperationCompleted == null)) {
                this.ExportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportOperationCompleted);
            }
            this.InvokeAsync("Export", new object[] {
                        commands,
                        filters,
                        topCount,
                        includeHeaders,
                        breakOnError}, this.ExportOperationCompleted, userState);
        }
        
        private void OnExportOperationCompleted(object arg) {
            if ((this.ExportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportCompleted(this, new ExportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/Import", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ImportResult[] Import(Command[] commands, Filter[] filters, [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")] [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)] string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget) {
            object[] results = this.Invoke("Import", new object[] {
                        commands,
                        filters,
                        data,
                        includedHeaders,
                        breakOnError,
                        breakOnIncorrectTarget});
            return ((ImportResult[])(results[0]));
        }
        
        /// <remarks/>
        public void ImportAsync(Command[] commands, Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget) {
            this.ImportAsync(commands, filters, data, includedHeaders, breakOnError, breakOnIncorrectTarget, null);
        }
        
        /// <remarks/>
        public void ImportAsync(Command[] commands, Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget, object userState) {
            if ((this.ImportOperationCompleted == null)) {
                this.ImportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportOperationCompleted);
            }
            this.InvokeAsync("Import", new object[] {
                        commands,
                        filters,
                        data,
                        includedHeaders,
                        breakOnError,
                        breakOnIncorrectTarget}, this.ImportOperationCompleted, userState);
        }
        
        private void OnImportOperationCompleted(object arg) {
            if ((this.ImportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportCompleted(this, new ImportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/Submit", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Content[] Submit(Command[] commands) {
            object[] results = this.Invoke("Submit", new object[] {
                        commands});
            return ((Content[])(results[0]));
        }
        
        /// <remarks/>
        public void SubmitAsync(Command[] commands) {
            this.SubmitAsync(commands, null);
        }
        
        /// <remarks/>
        public void SubmitAsync(Command[] commands, object userState) {
            if ((this.SubmitOperationCompleted == null)) {
                this.SubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitOperationCompleted);
            }
            this.InvokeAsync("Submit", new object[] {
                        commands}, this.SubmitOperationCompleted, userState);
        }
        
        private void OnSubmitOperationCompleted(object arg) {
            if ((this.SubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitCompleted(this, new SubmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/Login", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginResult Login(string name, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        name,
                        password});
            return ((LoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string name, string password) {
            this.LoginAsync(name, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string name, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        name,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/Logout", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Logout() {
            this.Invoke("Logout", new object[0]);
        }
        
        /// <remarks/>
        public void LogoutAsync() {
            this.LogoutAsync(null);
        }
        
        /// <remarks/>
        public void LogoutAsync(object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[0], this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/SetBusinessDate", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetBusinessDate(System.DateTime date) {
            this.Invoke("SetBusinessDate", new object[] {
                        date});
        }
        
        /// <remarks/>
        public void SetBusinessDateAsync(System.DateTime date) {
            this.SetBusinessDateAsync(date, null);
        }
        
        /// <remarks/>
        public void SetBusinessDateAsync(System.DateTime date, object userState) {
            if ((this.SetBusinessDateOperationCompleted == null)) {
                this.SetBusinessDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetBusinessDateOperationCompleted);
            }
            this.InvokeAsync("SetBusinessDate", new object[] {
                        date}, this.SetBusinessDateOperationCompleted, userState);
        }
        
        private void OnSetBusinessDateOperationCompleted(object arg) {
            if ((this.SetBusinessDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetBusinessDateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/SetLocaleName", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetLocaleName(string localeName) {
            this.Invoke("SetLocaleName", new object[] {
                        localeName});
        }
        
        /// <remarks/>
        public void SetLocaleNameAsync(string localeName) {
            this.SetLocaleNameAsync(localeName, null);
        }
        
        /// <remarks/>
        public void SetLocaleNameAsync(string localeName, object userState) {
            if ((this.SetLocaleNameOperationCompleted == null)) {
                this.SetLocaleNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetLocaleNameOperationCompleted);
            }
            this.InvokeAsync("SetLocaleName", new object[] {
                        localeName}, this.SetLocaleNameOperationCompleted, userState);
        }
        
        private void OnSetLocaleNameOperationCompleted(object arg) {
            if ((this.SetLocaleNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetLocaleNameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/typed/SetSchemaMode", RequestNamespace="http://www.acumatica.com/typed/", ResponseNamespace="http://www.acumatica.com/typed/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSchemaMode(SchemaMode mode) {
            this.Invoke("SetSchemaMode", new object[] {
                        mode});
        }
        
        /// <remarks/>
        public void SetSchemaModeAsync(SchemaMode mode) {
            this.SetSchemaModeAsync(mode, null);
        }
        
        /// <remarks/>
        public void SetSchemaModeAsync(SchemaMode mode, object userState) {
            if ((this.SetSchemaModeOperationCompleted == null)) {
                this.SetSchemaModeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchemaModeOperationCompleted);
            }
            this.InvokeAsync("SetSchemaMode", new object[] {
                        mode}, this.SetSchemaModeOperationCompleted, userState);
        }
        
        private void OnSetSchemaModeOperationCompleted(object arg) {
            if ((this.SetSchemaModeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchemaModeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class ProcessResult {
        
        private ProcessStatus statusField;
        
        private int secondsField;
        
        private string messageField;
        
        /// <remarks/>
        public ProcessStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public enum ProcessStatus {
        
        /// <remarks/>
        NotExists,
        
        /// <remarks/>
        InProcess,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Aborted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class LoginResult {
        
        private ErrorCode codeField;
        
        private string messageField;
        
        private string sessionField;
        
        /// <remarks/>
        public ErrorCode Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public enum ErrorCode {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        INVALID_CREDENTIALS,
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        INVALID_API_VERSION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class ImportResult {
        
        private bool processedField;
        
        private string errorField;
        
        private Value[] keysField;
        
        /// <remarks/>
        public bool Processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public Value[] Keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Value : Field {
        
        private string messageField;
        
        private bool isErrorField;
        
        private string errorLevelField;
        
        public Value() {
            this.isErrorField = false;
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorLevel {
            get {
                return this.errorLevelField;
            }
            set {
                this.errorLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Field : Command {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Answer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Action))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Key))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EveryValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Field))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Command {
        
        private string fieldNameField;
        
        private string objectNameField;
        
        private string valueField;
        
        private bool commitField;
        
        private bool ignoreErrorField;
        
        private Command linkedCommandField;
        
        private ElementDescriptor descriptorField;
        
        public Command() {
            this.commitField = false;
            this.ignoreErrorField = false;
        }
        
        /// <remarks/>
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Commit {
            get {
                return this.commitField;
            }
            set {
                this.commitField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IgnoreError {
            get {
                return this.ignoreErrorField;
            }
            set {
                this.ignoreErrorField = value;
            }
        }
        
        /// <remarks/>
        public Command LinkedCommand {
            get {
                return this.linkedCommandField;
            }
            set {
                this.linkedCommandField = value;
            }
        }
        
        /// <remarks/>
        public ElementDescriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class ElementDescriptor {
        
        private string displayNameField;
        
        private bool isDisabledField;
        
        private bool isRequiredField;
        
        private ElementTypes elementTypeField;
        
        private int lengthLimitField;
        
        private string inputMaskField;
        
        private string displayRulesField;
        
        private string[] allowedValuesField;
        
        private Container containerField;
        
        private string actionIconField;
        
        private int fieldPriorityField;
        
        private PXSpecialButtonType buttonTypeField;
        
        private string linkCommandField;
        
        private bool visibleField;
        
        private bool isTimeListField;
        
        private System.Nullable<bool> preserveTimeField;
        
        private string dependsOnField;
        
        private string stateColumnField;
        
        public ElementDescriptor() {
            this.isDisabledField = false;
            this.isRequiredField = false;
            this.elementTypeField = ElementTypes.String;
            this.lengthLimitField = 0;
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDisabled {
            get {
                return this.isDisabledField;
            }
            set {
                this.isDisabledField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ElementTypes.String)]
        public ElementTypes ElementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int LengthLimit {
            get {
                return this.lengthLimitField;
            }
            set {
                this.lengthLimitField = value;
            }
        }
        
        /// <remarks/>
        public string InputMask {
            get {
                return this.inputMaskField;
            }
            set {
                this.inputMaskField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayRules {
            get {
                return this.displayRulesField;
            }
            set {
                this.displayRulesField = value;
            }
        }
        
        /// <remarks/>
        public string[] AllowedValues {
            get {
                return this.allowedValuesField;
            }
            set {
                this.allowedValuesField = value;
            }
        }
        
        /// <remarks/>
        public Container Container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
            }
        }
        
        /// <remarks/>
        public string ActionIcon {
            get {
                return this.actionIconField;
            }
            set {
                this.actionIconField = value;
            }
        }
        
        /// <remarks/>
        public int FieldPriority {
            get {
                return this.fieldPriorityField;
            }
            set {
                this.fieldPriorityField = value;
            }
        }
        
        /// <remarks/>
        public PXSpecialButtonType ButtonType {
            get {
                return this.buttonTypeField;
            }
            set {
                this.buttonTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LinkCommand {
            get {
                return this.linkCommandField;
            }
            set {
                this.linkCommandField = value;
            }
        }
        
        /// <remarks/>
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTimeList {
            get {
                return this.isTimeListField;
            }
            set {
                this.isTimeListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> PreserveTime {
            get {
                return this.preserveTimeField;
            }
            set {
                this.preserveTimeField = value;
            }
        }
        
        /// <remarks/>
        public string DependsOn {
            get {
                return this.dependsOnField;
            }
            set {
                this.dependsOnField = value;
            }
        }
        
        /// <remarks/>
        public string StateColumn {
            get {
                return this.stateColumnField;
            }
            set {
                this.stateColumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public enum ElementTypes {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        AsciiString,
        
        /// <remarks/>
        StringSelector,
        
        /// <remarks/>
        ExplicitSelector,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Option,
        
        /// <remarks/>
        WideOption,
        
        /// <remarks/>
        Calendar,
        
        /// <remarks/>
        Action,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Container {
        
        private Field[] fieldsField;
        
        private string nameField;
        
        private Command[] serviceCommandsField;
        
        private Container[] childrenField;
        
        private string displayNameField;
        
        /// <remarks/>
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Command[] ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
        
        /// <remarks/>
        public Container[] Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public enum PXSpecialButtonType {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Save,
        
        /// <remarks/>
        SaveNotClose,
        
        /// <remarks/>
        Cancel,
        
        /// <remarks/>
        Refresh,
        
        /// <remarks/>
        Report,
        
        /// <remarks/>
        First,
        
        /// <remarks/>
        Next,
        
        /// <remarks/>
        Prev,
        
        /// <remarks/>
        Last,
        
        /// <remarks/>
        Insert,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        Approve,
        
        /// <remarks/>
        ApproveAll,
        
        /// <remarks/>
        Process,
        
        /// <remarks/>
        ProcessAll,
        
        /// <remarks/>
        EditDetail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class NewRow : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Answer : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Action : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Key : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Parameter : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class DeleteRow : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class RowNumber : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class EveryValue : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Attachment : Field {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Filter {
        
        private Field fieldField;
        
        private FilterCondition conditionField;
        
        private object valueField;
        
        private object value2Field;
        
        private int openBracketsField;
        
        private int closeBracketsField;
        
        private FilterOperator operatorField;
        
        /// <remarks/>
        public Field Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public FilterCondition Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public object Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
            }
        }
        
        /// <remarks/>
        public int OpenBrackets {
            get {
                return this.openBracketsField;
            }
            set {
                this.openBracketsField = value;
            }
        }
        
        /// <remarks/>
        public int CloseBrackets {
            get {
                return this.closeBracketsField;
            }
            set {
                this.closeBracketsField = value;
            }
        }
        
        /// <remarks/>
        public FilterOperator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public enum FilterCondition {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Contain,
        
        /// <remarks/>
        StartsWith,
        
        /// <remarks/>
        EndsWith,
        
        /// <remarks/>
        NotContain,
        
        /// <remarks/>
        Between,
        
        /// <remarks/>
        IsNull,
        
        /// <remarks/>
        IsNotNull,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public enum FilterOperator {
        
        /// <remarks/>
        And,
        
        /// <remarks/>
        Or,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class TemplateServiceCommands {
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Template {
        
        private string displayNameField;
        
        private Field nameField;
        
        private Field isDefaultField;
        
        private Field isSharedField;
        
        private TemplateServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Field IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        public Field IsShared {
            get {
                return this.isSharedField;
            }
            set {
                this.isSharedField = value;
            }
        }
        
        /// <remarks/>
        public TemplateServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class ReportResultsServiceCommands {
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class ReportResults {
        
        private string displayNameField;
        
        private Field pdfContentField;
        
        private Field htmlContentField;
        
        private Field preProcessField;
        
        private ReportResultsServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field PdfContent {
            get {
                return this.pdfContentField;
            }
            set {
                this.pdfContentField = value;
            }
        }
        
        /// <remarks/>
        public Field HtmlContent {
            get {
                return this.htmlContentField;
            }
            set {
                this.htmlContentField = value;
            }
        }
        
        /// <remarks/>
        public Field PreProcess {
            get {
                return this.preProcessField;
            }
            set {
                this.preProcessField = value;
            }
        }
        
        /// <remarks/>
        public ReportResultsServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class FiltersServiceCommands {
        
        private NewRow newRowField;
        
        private RowNumber rowNumberField;
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        /// <remarks/>
        public NewRow NewRow {
            get {
                return this.newRowField;
            }
            set {
                this.newRowField = value;
            }
        }
        
        /// <remarks/>
        public RowNumber RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Filters {
        
        private string displayNameField;
        
        private Field conditionField;
        
        private Field dataFieldField;
        
        private Field operatorField;
        
        private Field openBracesField;
        
        private Field closeBracesField;
        
        private Field valueField;
        
        private Field value2Field;
        
        private FiltersServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public Field DataField {
            get {
                return this.dataFieldField;
            }
            set {
                this.dataFieldField = value;
            }
        }
        
        /// <remarks/>
        public Field Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public Field OpenBraces {
            get {
                return this.openBracesField;
            }
            set {
                this.openBracesField = value;
            }
        }
        
        /// <remarks/>
        public Field CloseBraces {
            get {
                return this.closeBracesField;
            }
            set {
                this.closeBracesField = value;
            }
        }
        
        /// <remarks/>
        public Field Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public Field Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
            }
        }
        
        /// <remarks/>
        public FiltersServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class SortingServiceCommands {
        
        private NewRow newRowField;
        
        private RowNumber rowNumberField;
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        /// <remarks/>
        public NewRow NewRow {
            get {
                return this.newRowField;
            }
            set {
                this.newRowField = value;
            }
        }
        
        /// <remarks/>
        public RowNumber RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Sorting {
        
        private string displayNameField;
        
        private Field dataFieldField;
        
        private Field sortOrderField;
        
        private SortingServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field DataField {
            get {
                return this.dataFieldField;
            }
            set {
                this.dataFieldField = value;
            }
        }
        
        /// <remarks/>
        public Field SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        public SortingServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class MailSettingsServiceCommands {
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class MailSettings {
        
        private string displayNameField;
        
        private Field toField;
        
        private Field ccField;
        
        private Field bccField;
        
        private Field subjectField;
        
        private Field bodyField;
        
        private Field templateIDField;
        
        private Field formatField;
        
        private Field activitySourceField;
        
        private Field parentSourceField;
        
        private MailSettingsServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public Field Cc {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
            }
        }
        
        /// <remarks/>
        public Field Bcc {
            get {
                return this.bccField;
            }
            set {
                this.bccField = value;
            }
        }
        
        /// <remarks/>
        public Field Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public Field Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public Field TemplateID {
            get {
                return this.templateIDField;
            }
            set {
                this.templateIDField = value;
            }
        }
        
        /// <remarks/>
        public Field Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public Field ActivitySource {
            get {
                return this.activitySourceField;
            }
            set {
                this.activitySourceField = value;
            }
        }
        
        /// <remarks/>
        public Field ParentSource {
            get {
                return this.parentSourceField;
            }
            set {
                this.parentSourceField = value;
            }
        }
        
        /// <remarks/>
        public MailSettingsServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class CommonSettingsServiceCommands {
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class CommonSettings {
        
        private string displayNameField;
        
        private Field viewPdfField;
        
        private Field pdfCompressedField;
        
        private Field pdfFontEmbeddedField;
        
        private Field printAllPagesField;
        
        private Field deletedRecordsField;
        
        private CommonSettingsServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field ViewPdf {
            get {
                return this.viewPdfField;
            }
            set {
                this.viewPdfField = value;
            }
        }
        
        /// <remarks/>
        public Field PdfCompressed {
            get {
                return this.pdfCompressedField;
            }
            set {
                this.pdfCompressedField = value;
            }
        }
        
        /// <remarks/>
        public Field PdfFontEmbedded {
            get {
                return this.pdfFontEmbeddedField;
            }
            set {
                this.pdfFontEmbeddedField = value;
            }
        }
        
        /// <remarks/>
        public Field PrintAllPages {
            get {
                return this.printAllPagesField;
            }
            set {
                this.printAllPagesField = value;
            }
        }
        
        /// <remarks/>
        public Field DeletedRecords {
            get {
                return this.deletedRecordsField;
            }
            set {
                this.deletedRecordsField = value;
            }
        }
        
        /// <remarks/>
        public CommonSettingsServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class ParametersServiceCommands {
        
        private EveryValue everyDocumentTypeField;
        
        private EveryValue everyReferenceNumberField;
        
        private NewRow newRowField;
        
        private RowNumber rowNumberField;
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        /// <remarks/>
        public EveryValue EveryDocumentType {
            get {
                return this.everyDocumentTypeField;
            }
            set {
                this.everyDocumentTypeField = value;
            }
        }
        
        /// <remarks/>
        public EveryValue EveryReferenceNumber {
            get {
                return this.everyReferenceNumberField;
            }
            set {
                this.everyReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public NewRow NewRow {
            get {
                return this.newRowField;
            }
            set {
                this.newRowField = value;
            }
        }
        
        /// <remarks/>
        public RowNumber RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Parameters {
        
        private string displayNameField;
        
        private Field documentTypeField;
        
        private Field referenceNumberField;
        
        private ParametersServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public Field ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public ParametersServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Actions {
        
        private Action saveLocField;
        
        private Action reloadField;
        
        private Action refreshParamsField;
        
        private Action loadParamsField;
        
        private Action templateSaveField;
        
        private Action templateRemoveField;
        
        private Action templateSelectField;
        
        private Action mailSendField;
        
        private Action navigateField;
        
        private Action templateScheduleField;
        
        /// <remarks/>
        public Action SaveLoc {
            get {
                return this.saveLocField;
            }
            set {
                this.saveLocField = value;
            }
        }
        
        /// <remarks/>
        public Action Reload {
            get {
                return this.reloadField;
            }
            set {
                this.reloadField = value;
            }
        }
        
        /// <remarks/>
        public Action RefreshParams {
            get {
                return this.refreshParamsField;
            }
            set {
                this.refreshParamsField = value;
            }
        }
        
        /// <remarks/>
        public Action LoadParams {
            get {
                return this.loadParamsField;
            }
            set {
                this.loadParamsField = value;
            }
        }
        
        /// <remarks/>
        public Action TemplateSave {
            get {
                return this.templateSaveField;
            }
            set {
                this.templateSaveField = value;
            }
        }
        
        /// <remarks/>
        public Action TemplateRemove {
            get {
                return this.templateRemoveField;
            }
            set {
                this.templateRemoveField = value;
            }
        }
        
        /// <remarks/>
        public Action TemplateSelect {
            get {
                return this.templateSelectField;
            }
            set {
                this.templateSelectField = value;
            }
        }
        
        /// <remarks/>
        public Action MailSend {
            get {
                return this.mailSendField;
            }
            set {
                this.mailSendField = value;
            }
        }
        
        /// <remarks/>
        public Action Navigate {
            get {
                return this.navigateField;
            }
            set {
                this.navigateField = value;
            }
        }
        
        /// <remarks/>
        public Action TemplateSchedule {
            get {
                return this.templateScheduleField;
            }
            set {
                this.templateScheduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public partial class Content {
        
        private Actions actionsField;
        
        private Parameters parametersField;
        
        private CommonSettings commonSettingsField;
        
        private MailSettings mailSettingsField;
        
        private Sorting sortingField;
        
        private Filters filtersField;
        
        private ReportResults reportResultsField;
        
        private Template templateField;
        
        /// <remarks/>
        public Actions Actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        public Parameters Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        public CommonSettings CommonSettings {
            get {
                return this.commonSettingsField;
            }
            set {
                this.commonSettingsField = value;
            }
        }
        
        /// <remarks/>
        public MailSettings MailSettings {
            get {
                return this.mailSettingsField;
            }
            set {
                this.mailSettingsField = value;
            }
        }
        
        /// <remarks/>
        public Sorting Sorting {
            get {
                return this.sortingField;
            }
            set {
                this.sortingField = value;
            }
        }
        
        /// <remarks/>
        public Filters Filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
        
        /// <remarks/>
        public ReportResults ReportResults {
            get {
                return this.reportResultsField;
            }
            set {
                this.reportResultsField = value;
            }
        }
        
        /// <remarks/>
        public Template Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/typed/")]
    public enum SchemaMode {
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Detailed,
        
        /// <remarks/>
        DetailedWithHidden,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ClearCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetProcessStatusCompletedEventHandler(object sender, GetProcessStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProcessStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProcessStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcessResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcessResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetScenarioCompletedEventHandler(object sender, GetScenarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScenarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScenarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Command[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Command[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSchemaCompletedEventHandler(object sender, GetSchemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Content Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Content)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SetSchemaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExportCompletedEventHandler(object sender, ExportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ImportCompletedEventHandler(object sender, ImportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ImportResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ImportResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SubmitCompletedEventHandler(object sender, SubmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Content[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Content[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LogoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SetBusinessDateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SetLocaleNameCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SetSchemaModeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591