<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>PhoneRepairShop_Code.Tests</RootNamespace>
    <AssemblyName>PhoneRepairShop_Code.Tests</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <FileVersion>26.100.0217</FileVersion>
    <InformationalVersion>26.100.0217</InformationalVersion>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <Copyright>Copyright © 2005-2026 Acumatica, Inc. All rights reserved.</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PhoneRepairShop_Code\PhoneRepairShop_Code.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Autofac">
      <HintPath>..\..\..\..\Bin\Autofac.dll</HintPath>
    </Reference>
    <Reference Include="PX.Common">
      <HintPath>..\..\..\..\Bin\PX.Common.dll</HintPath>
    </Reference>
    <Reference Include="PX.Common.Std">
      <HintPath>..\..\..\..\Bin\PX.Common.Std.dll</HintPath>
    </Reference>
    <Reference Include="PX.CS.Contracts">
      <HintPath>..\..\..\..\Bin\PX.CS.Contracts.dll</HintPath>
    </Reference>
    <Reference Include="PX.Data">
      <HintPath>..\..\..\..\Bin\PX.Data.dll</HintPath>
    </Reference>
    <Reference Include="PX.Data.BQL.Fluent">
      <HintPath>..\..\..\..\Bin\PX.Data.BQL.Fluent.dll</HintPath>
    </Reference>
    <Reference Include="PX.Objects">
      <HintPath>..\..\..\..\Bin\PX.Objects.dll</HintPath>
    </Reference>
    <Reference Include="PX.Web.Customization">
      <HintPath>..\..\..\..\Bin\PX.Web.Customization.dll</HintPath>
    </Reference>
    <Reference Include="PX.Tests.Unit">
      <HintPath>..\..\..\..\Bin\PX.Tests.Unit.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>